---
name: build
on: [deployment, push]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3'

      - name: Install dependencies
        run: |
          python3 -m pip install -r molecule/requirements.txt

      - name: Install galaxy roles
        run: |
          ansible-galaxy install -r molecule/default/requirements.yml
          ansible-galaxy install git+https://github.com/${{ github.repository }},${{ github.sha }}

      - name: Execulte ansible-lint
        run: |
          ansible-lint

      - name: Show ansible-lint version
        run: |
          ansible-lint --version
          ansible-community --version

  molecule:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3'

      - name: Install dependencies
        run: |
          python3 -m pip install -r molecule/requirements.txt

      - name: Test with Molecule
        env:
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_IMAGE: 'ghcr.io/docker-images-mamono210/ansible-test/centos-stream8:latest'
          MOLECULE_NO_LOG: False
          PROFILE_TASKS_SORT_ORDER: 'none'
          PROFILE_TASKS_TASK_OUTPUT_LIMIT: '100'
          PY_COLORS: '1'
          TZ: 'Asia/Tokyo'
        run: |
          molecule test

      - name: Show Ansible version
        run: |
          pip list | grep ansible \
          | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
          | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
          | GREP_COLORS='mt=01;33' egrep --color=always 'ansible.* '
          ansible --version

      - name: Show Molecule version
        run: |
          molecule --version
        env:
          PY_COLORS: '1'

  trailing-whitespace:
    name: Find Trailing Whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: harupy/find-trailing-whitespace@56310d70ae8fd21afec8d4307d2d9ab6c15e7c5d

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Execute yamllint
        run: yamllint *

      - name: Show yamllint version
        run: yamllint --version
